"""Alembic async migration environment for Memex.

Supports:
- Async SQLAlchemy engine (asyncpg)
- SQLModel metadata (pgvector Vector columns)
- Advisory locking to prevent concurrent migration races
- pgvector autogenerate (render_item / compare_type)
"""

import asyncio
import logging
from logging.config import fileConfig

from alembic import context
from pgvector.sqlalchemy import Vector
from sqlalchemy import pool, text
from sqlalchemy.ext.asyncio import create_async_engine
from sqlmodel import SQLModel

# Import all models so SQLModel.metadata is fully populated.
import memex_core.memory.sql_models  # noqa: F401
from memex_core.storage.db_url import get_database_url

logger = logging.getLogger('alembic.env')

# Alembic Config object — provides access to alembic.ini values.
config = context.config

# Interpret the config file for Python logging (if present).
# disable_existing_loggers=False is required so we don't disable every
# logger created before this point. The default (True) would mark
# every already-instantiated logger (memex_eval.*, structlog-bridged, etc.)
# as ``disabled=True``, which silently swallows their records for the rest
# of the process — including any ``caplog`` capture in tests.
if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# The metadata object used for autogenerate support.
target_metadata = SQLModel.metadata

# Advisory lock ID used to serialize migrations across workers.
MIGRATION_LOCK_ID = 720_701


# ---------------------------------------------------------------------------
# pgvector autogenerate helpers
# ---------------------------------------------------------------------------


def include_object(object, name, type_, reflected, compare_to):
    """Skip the alembic_version table during autogenerate."""
    if type_ == 'table' and name == 'alembic_version':
        return False
    return True


def render_item(type_, obj, autogen_context):
    """Render Vector columns correctly in autogenerated migrations."""
    if type_ == 'type' and isinstance(obj, Vector):
        autogen_context.imports.add('from pgvector.sqlalchemy import Vector')
        return f'Vector({obj.dim})'
    return False


def compare_type(context, inspected_column, metadata_column, inspected_type, metadata_type):
    """Prevent false positives for Vector columns (reflected as USER-DEFINED)."""
    if isinstance(metadata_type, Vector):
        return False
    return None


def _resolve_url() -> str:
    """Resolve the database URL, with alembic.ini as final fallback."""
    try:
        return get_database_url()
    except RuntimeError:
        ini_url = config.get_main_option('sqlalchemy.url')
        if ini_url:
            return ini_url
        raise


_AUTOGEN_KWARGS = {
    'include_object': include_object,
    'render_item': render_item,
    'compare_type': compare_type,
}


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — emit SQL to stdout.

    This configures the context with just a URL and not an Engine,
    though an Engine is acceptable here as well. By skipping engine
    creation we don't even need a DBAPI to be available.
    """
    url = _resolve_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={'paramstyle': 'named'},
        **_AUTOGEN_KWARGS,
    )

    with context.begin_transaction():
        context.run_migrations()


def _is_fresh_db(connection) -> bool:
    """True when the public schema has zero application tables."""
    result = connection.execute(
        text(
            'SELECT NOT EXISTS ('
            '  SELECT 1 FROM information_schema.tables'
            "  WHERE table_schema = 'public' AND table_name = 'vaults'"
            ')'
        )
    )
    return bool(result.scalar())


def _bootstrap_fresh_db(connection) -> None:
    """Fast-path for a brand-new database.

    ``SQLModel.metadata.create_all`` builds every table from the current
    Python model definitions — including columns added by later
    migrations. Running the migration chain after that would fail on
    every ``ALTER TABLE ADD COLUMN`` because the column already exists.

    Instead: create everything in one shot, stamp alembic at HEAD, done.
    Data-carrying migrations (backfills) are no-ops on an empty DB.
    """
    connection.execute(text('CREATE EXTENSION IF NOT EXISTS vector'))
    connection.execute(text('CREATE EXTENSION IF NOT EXISTS pg_trgm'))
    SQLModel.metadata.create_all(bind=connection)

    script_dir = context.script
    head = script_dir.get_current_head()
    connection.execute(
        text(
            'CREATE TABLE IF NOT EXISTS alembic_version ('
            '  version_num VARCHAR(32) NOT NULL,'
            '  CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)'
            ')'
        )
    )
    connection.execute(text('DELETE FROM alembic_version'))
    connection.execute(
        text('INSERT INTO alembic_version (version_num) VALUES (:rev)'),
        {'rev': head},
    )
    logger.info('Fresh database: created all tables via create_all, stamped at %s', head)


def do_run_migrations(connection):
    """Run migrations with an active connection.

    On a fresh database (no application tables), takes a shortcut:
    ``create_all`` + stamp HEAD. On an existing database, runs the
    normal alembic migration chain.
    """
    if _is_fresh_db(connection):
        _bootstrap_fresh_db(connection)
        return

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        **_AUTOGEN_KWARGS,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in 'online' mode with an async engine.

    Acquires a PostgreSQL advisory lock first to prevent concurrent
    migration execution across multiple workers.
    """
    connectable = create_async_engine(
        _resolve_url(),
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        # Acquire session-level advisory lock to serialize migrations.
        # Released automatically when the connection/session closes.
        await connection.execute(text(f'SELECT pg_advisory_lock({MIGRATION_LOCK_ID})'))
        await connection.run_sync(do_run_migrations)
        # Alembic's begin_transaction() creates a SAVEPOINT inside the
        # implicit transaction from connect(). Releasing the savepoint
        # does NOT commit the outer transaction — we must do it explicitly.
        await connection.commit()

    await connectable.dispose()


def run_migrations_online() -> None:
    """Entry point for online migrations — delegates to async runner."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
